### ISSUE TITLE
Not able to see what I am typing 

### ISSUE THREAD

**Issue by Janak-Nirmal** [ren6/RKRichTextView#1]
Thanks for this control it works awesome. Though I hate noticed there is one issue in **iOS7** beta. May be this is too early but just to inform you there is a problem in html rendering. 

When I have completed on screen space and scrolling is enabled after few lines of text written, text font is not being displayed while I am typing and is viewable after entering to next line by pressing return key.

**Comment by ren6** [comment]
Fixed
